# Generated by Django 5.2.7 on 2025-11-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='image_url',
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='watch_images/')),
                ('order', models.IntegerField(default=0, help_text='Image order (0 is primary)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='watches.watch')),
            ],
            options={
                'verbose_name': 'Watch Image',
                'verbose_name_plural': 'Watch Images',
                'ordering': ['order'],
            },
        ),
    ]
